<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de">
  <context>
    <name>QuickTaskDialog</name>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="42" />
      <source>Szybkie dodawanie zadania</source>
      <translation>Aufgabe schnell hinzufügen</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="62" />
      <source>Zadanie:</source>
      <translation>Aufgabe:</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="67" />
      <source>Wpisz treść zadania...</source>
      <translation>Aufgabeninhalt eingeben...</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="84" />
      <source>Dodaj zadanie</source>
      <translation>Aufgabe hinzufügen</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="406" />
      <location filename="..\..\ui\quick_task_dialog.py" line="89" />
      <source>Anuluj</source>
      <translation>Abbrechen</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="177" />
      <source>Wpisz</source>
      <translation>Eingeben</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="210" />
      <source>Brak opcji</source>
      <translation>Keine Optionen</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="213" />
      <source>Błąd ładowania</source>
      <translation>Ladefehler</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="215" />
      <source>Brak konfiguracji</source>
      <translation>Keine Konfiguration</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="288" />
      <location filename="..\..\ui\quick_task_dialog.py" line="280" />
      <location filename="..\..\ui\quick_task_dialog.py" line="226" />
      <source>Błąd</source>
      <translation>Fehler</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="226" />
      <source>Wpisz treść zadania!</source>
      <translation>Bitte Aufgabeninhalt eingeben!</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="274" />
      <source>Sukces</source>
      <translation>Erfolg</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="274" />
      <source>Zadanie zostało dodane!</source>
      <translation>Aufgabe wurde hinzugefügt!</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="280" />
      <source>Nie udało się dodać zadania do bazy danych!</source>
      <translation>Aufgabe konnte nicht zur Datenbank hinzugefügt werden!</translation>
    </message>
    <message>
      <location filename="..\..\ui\quick_task_dialog.py" line="288" />
      <source>Wystąpił błąd podczas dodawania zadania:</source>
      <translation>Beim Hinzufügen der Aufgabe ist ein Fehler aufgetreten:</translation>
    </message>
  </context>
</TS>
